### PR TITLE
adding five new calendars

### PR DESCRIPTION
**Pull request by eddelbuettel**
Here are five new calendars.  No tests for them yet, guess we need that too.

### CODE REVIEW

**Comment by pcaspers** [comment]
merged via 9aade299

**Comment by pcaspers** [comment]
you have the test suite binary in your branch, therefore I merged your changes manually

**Comment by pcaspers** [comment]
I also added ```quantlibtestsuite``` to gitignore, since this is also the binary name I choose in this project (same as the cpp file name)

**Comment by pcaspers** [comment]
Finally, I added the unit tests for calendars from QuantLib, two errors showed up

```
Testing China Shanghai Stock Exchange holiday list...
./calendars.hpp:1698: fatal error: in "QuantLib test suite/Calendar tests/QuantLib__detail__quantlib_test_case(&CalendarTest__testChinaSSE)": there were 66 expected holidays, while there are 50 calculated holidays
Testing China Inter Bank working weekends list...
./calendars.hpp:1754: fatal error: in "QuantLib test suite/Calendar tests/QuantLib__detail__quantlib_test_case(&CalendarTest__testChinaIB)": there were 21 expected working weekends, while there are 16 calculated working weekends
```

After updating china.hpp to the latest QuantLib version, the errors disappeared.

**Comment by eddelbuettel** [comment]
Sorry about the binary. I am usually more careful / attentive via magit.

**Comment by pcaspers** [comment]
No problem, thanks for the new calendars.

**Comment by eddelbuettel** [comment]
Also weird that tests failed for you.  The only reason the binary was created was that I tried to be careful and test before committing.  And I recall it passing for me.  Odd.

`china.hpp` was weird anyway as it ended in 2016.  Should have alerted me.  Now it ends in 2017. No forward looking calculations?

Thanks also for adding the bespoke and joint calendar.  I'll see if I can cook up an interface for RcppQuantuccia.

**Comment by eddelbuettel** [comment]
Question I had for you:  how is the update going to work when QuantLib itself updates?   "Careful" and by hand, or do you better more industrial machinery?

**Comment by pcaspers** [comment]
you didn't had the calendar tests, did you?

**Comment by pcaspers** [comment]
At the moment I'd diff say 1.10 against 1.9 and update the changed files by hand. Some scripting solution would be nice, but the project didn't start that systematically.

**Comment by eddelbuettel** [comment]
I only had some initial tests in RcppQuantuccia, and in Quantuccia I must have had "something" as I saw a few lines of "all is good".  But I was current with what your repo had -- so I probably only had whatever fragments you had put in for US and TARGET.  Hence no China tests which would explain it.

**Comment by pcaspers** [comment]
ok: in any case, after the full sync all should be fine on your side now?

**Comment by eddelbuettel** [comment]
Am traveling right now (out at a college soccer tournament where daughter #1 is playing) so I didn't run it yet.

And just tried for a few minutes and got linking issues.  Hm.

**Comment by pcaspers** [comment]
Linking issues, hm, that’s not the idea…
I realised today that the unit test headers are actually defining symbols, so they should only compiled once. But this is normally the case, they are only included from quantlibtestsuite.cpp, aren’t of any use elsewhere. So I’d leave them alone.

Good luck for #1!

**Comment by eddelbuettel** [comment]
I am a bit puzzled too as it was easier to build before.   We should probably stick a `Makefile` in that directory.

Team won last eve when we weren't here yet and just had a nice win against a D1 ("big school") team -- keeping the unbeaten streak from last fall.  One more game in a few hours and then either head home or stay for tomorrow's games...

**Comment by pcaspers** [comment]
Yeah, a simple Makefile and a VC project / solution, that would make sense. That’s something for next weekend maybe.

Sounds very impressive, hope it works out today…

**Comment by eddelbuettel** [comment]
I think I was just being silly ... as I didn't remember we had the proper test recipe in the Travis file.  Thanks for adding all the tests.  Very nice to have.

I am now a little ahead. A [comparison is here](https://github.com/pcaspers/Quantuccia/compare/master...eddelbuettel:master).  Shall I PR that so that we once again at the same level?

**Comment by pcaspers** [comment]
This looks I have the binary quantlibtestsuite added to .gitignore and the dummy file (that was a test if travis is triggered by a commit), so no need that you send me a PR?

**Comment by eddelbuettel** [comment]
I _was_ current with you yet somehow [dummy is clearly still there](https://github.com/pcaspers/Quantuccia/blob/master/dummy). 

The addition of quantlibtestsuite to `.gitignore` was indeed an error. I didn't see it in there at the bottom as the top had  a section dedicated to build outputs and artifcacts -- my `.gitignore` files tend not to be that involved over multiple screens.   Anyway, now reverted, and here is an [updated comparison](https://github.com/pcaspers/Quantuccia/compare/master...eddelbuettel:master).

**Comment by pcaspers** [comment]
yeah that makes sense, so we are in sync except I have still that empty dummy file, can just just open a PR on the last comparison you send, then I'll merge.

**Comment by eddelbuettel** [comment]
Well, AFAIK the created PRs are always between repos / branches so I cannot cherry pick just that single commit over to you as a PR.   

Git is smart enough to see that is the only _actual_ change (cf the link above) so I could still send you a PR and you could, if you prefer, squash-merge it making it one commit (simple toggle on the button).   

Else I think you would have to cherry pick the commit from my repo.

**Comment by pcaspers** [comment]
I tested in a copy of the repo to merge with your master. At first sight that works, it seems to remove the dummy file and not to change anything else. However going back to the commit before you deleted the binary in your repo, creates the binary in my test-suite folder, so actually I get the whole history from your branch. So just looking at the diff of a PR can be misleading obviously.

Now I just removed the dummy file manually. You should be able to merge with my master without any conflicts I guess (or trvival to solve conflicts).

**Comment by eddelbuettel** [comment]
I really do not understand why we are making this so complicated. You *obviously* created *another* required merge commit for me by doubling the commit I had already done.  That is *the definition of a conflict*:  both of us hitting the same file.

I give up.

**Comment by pcaspers** [comment]
If I cherry-pick your b079fcb46e I get the double entry in .gitignore, since both the deletion of dummy and adding the entry to .gitignore are in the same commit. Yes I could cherry-pick 91a2b13f thereafter to clean up again, but that's not really the idea is it?

If you on the other hand just merge my master (now or later), it's automatic, there is no conflict. I thought there might be, but git doesn't regard a deletion of a file on two branches as a conflict (which makes sense I think).

Now the real problem is you can't send any PR from your master without making me merging your history with the 2.5M binary in it, which I don't want. Sure I could cherry pick the commits I want, but it would make more sense if you dump your current master and check out a fresh version. Now is the time since the both repos are really identical otherwise from what I see.

**Pull request closed without merging**
