### PR TITLE
Enable Travis

### PR DESCRIPTION
**Pull request by eddelbuettel**
You may need to 'turn on' Travis for your account as well as the repo.  Then, once this `.travis.yml` is added builds will be triggered on each commit.    

My log of builds is [here](https://travis-ci.org/eddelbuettel/Quantuccia) with an initial fail when I had builds already turned on, pushed your changes (sans `.travis.yml`) which failed and then an initial failure when I had not yet installed Boost.   The third worked, but misspelled log_level as log-level so I will run another in a second.

### CODE REVIEW

**Comment by pcaspers** [comment]
works like a charm, thanks Dirk

**Comment by eddelbuettel** [comment]
Perfect.  If you want to play along from the other side, I just pushed to the still small [RcppQuantuccia](https://github.com/eddelbuettel/rcppquantuccia) repo.   The main thing is that I added the date converters from RQuantLib so I can now add more date utilities functions.  Perfect for noodling with on the (short) commuter train.

But ... I have to ask:  What's the story with the name?

**Comment by pcaspers** [comment]
Well, Quantuccia = little sister of QuantLib. Cute, isn't it?

**Comment by pcaspers** [comment]
I saw you copied the source to the Rccp repo. Would it also be possible to use a git submodule to keep the source in sync?

**Comment by eddelbuettel** [comment]
Very cute!  But I just don't any Italian. Google Translate suggests _sorellina_ for _little sister_.

In theory, sub-modules would work.  In practice copies are just fine.  Did the same with a bunch of other repos, and have friends/acquaintances who uses submodules a lot at first and eventually gave up even between their own repos.

**Comment by pcaspers** [comment]
No objection, but remember to play back new material to the mother repo.

Is there anything that would be particularly attractive for your RccpQuantuccia project, like the other calendars or something else?

**Comment by eddelbuettel** [comment]
I think I will try to get as much calendaring to work as I have over in RQuantLib and will report back as I make progress.  More to follow.

Just in from the first 12 miler in about a year ...

**Comment by eddelbuettel** [comment]
Quick update. 

[RcppQuantuccia](https://github.com/eddelbuettel/rcppquantuccia) is slowly getting there for a 0.0.1 release.  I have the calendaring functionality that RQuantLib has now, plus some tests.

Some open questions:
- shall I send you a few PRs adding a calendar or two (maybe for G7 countries?) 
- or shall we just document who folks could add calendars locally?
- I used the Date type so far but I am thinking I should just permanently enable the intra-day `#define` and use Datetime on the R side, not Date.  

Thoughts?

**Comment by pcaspers** [comment]
Great. Yes please send PRs with your extensions, the calendars folder is still fairly empty. About the high resolution date, I didn't test it. Does it create a dependency to Boost.date_time (which is not header only)?

**Comment by eddelbuettel** [comment]
I don't think it pulls in Boost date_time as a linking requirement because Boost remains header only in RQuantLib as well where I have enable the flag.  I'll test that.  But one step at a time...

Do you have any feel for _which_ calendars would make a best first set?  I live off US::NYSE which is already in so <shrugs> ...

**Comment by pcaspers** [comment]
this would be my short list

#include <ql/time/calendars/australia.hpp>
#include <ql/time/calendars/canada.hpp>
#include <ql/time/calendars/china.hpp>
#include <ql/time/calendars/czechrepublic.hpp>
#include <ql/time/calendars/denmark.hpp>
#include <ql/time/calendars/finland.hpp>
#include <ql/time/calendars/germany.hpp>
#include <ql/time/calendars/hongkong.hpp>
#include <ql/time/calendars/hungary.hpp>
#include <ql/time/calendars/iceland.hpp>
#include <ql/time/calendars/india.hpp>
#include <ql/time/calendars/indonesia.hpp>
#include <ql/time/calendars/italy.hpp>
#include <ql/time/calendars/japan.hpp>
#include <ql/time/calendars/mexico.hpp>
#include <ql/time/calendars/newzealand.hpp>
#include <ql/time/calendars/norway.hpp>
#include <ql/time/calendars/poland.hpp>
#include <ql/time/calendars/russia.hpp>
#include <ql/time/calendars/southkorea.hpp>
#include <ql/time/calendars/sweden.hpp>
#include <ql/time/calendars/switzerland.hpp>
#include <ql/time/calendars/taiwan.hpp>
#include <ql/time/calendars/target.hpp>
#include <ql/time/calendars/turkey.hpp>
#include <ql/time/calendars/unitedkingdom.hpp>
#include <ql/time/calendars/unitedstates.hpp>

**Comment by eddelbuettel** [comment]
That's work :)

Rome wasn't built in a day, but I'll get there.  I presume this is not too urgent?

**Comment by pcaspers** [comment]
no, it's not urgent at all for me, and I can do (part of) the work. I will start at the bottom of the list during the next days, let's talk in any case before we reach japan... :-)

**Comment by eddelbuettel** [comment]
Well US in in, and as I realized just yesterday the right way too with Settlement, NYSE, GvmtBonds and NERC.  So I figured next might be Japan/China as well as UK/DE/FR. After that I may sit back and wait for PRs :)

**Comment by pcaspers** [comment]
alright so, I'll wait how it grows on your side, you have the more immediate use case for it anyway

**Comment by eddelbuettel** [comment]
Sounds good. Earlier today I looked into using intra-day times. For the calendaring it doesn't make much of a difference.  The one function where it could (`advance` given $N$ steps of a given unit) only goes down to days.  So next focus may just be to get what I have onto CRAN as 0.0.1 and then add a few calendars.

**Pull request merged**
