### PR TITLE
Partially resolved linking problem, all all.hpp have been added

### PR DESCRIPTION
**Pull request by rcalxrc08**
Hi,
I modified the following implementation because i found no workaround in order to keep the implementation unchanged:
1) the first one is in file "lecuyeruniformrng.hpp", i had to change the static member "maxRandom" in a static method that returns the same value.
2) the second is in file "bivariatenormaldistribution.hpp", i had to move the implementation of the members x and y inside the function that uses them.
3) i had to move the "implementation" of PrimeNumbers::primeNumbers_ inside the quantlibtestsuite.cpp file, i found no workaround to solve this.
4)i had to move the implementation of some methods of the PriceSetter class inside a new file called "pricersetter.hpp" to solve a multiple include problem.

The other changes have been done in order to make the library compiling.

### CODE REVIEW

**Comment by pcaspers** [comment]
Thanks. Concerning 3) do you think we can make PrimeNumbers a singleton that stores the already computed vector as a (non-static) member variable? Although this would change the interface I'd like that better than having to add this global variable to each application you compile. I guess PrimeNumbers is mostly a helper class for the RSG's that use it anyway.

**Comment by pcaspers** [comment]
I also added a check for c++03 to travis, there is one warning showing up, but I think this is easy to mitigate by making it a function returning the constant

**Comment by pcaspers** [comment]
Concerning 4), how does this work, i.e. if I want to use setCouponPricer(), do I have to include the additional file pricersetter.hpp? Why do we have to split the original file couponpricer.hpp?

**Comment by rcalxrc08** [comment]
Hi,
Regarding 3) i think that the singleton is a nice solution, my solution was only to make the library compile.
Regarding 4) i had to split the original file because there where a "chain include problem".
if i remember well couponpricer.hpp was including rangeaccrual.hpp and also the converse.

**Comment by pcaspers** [comment]
4) should rangeaccrual.hpp then include the new pricersetter.hpp and couponpricer.hpp as well include pricersetter.hpp, so that nothing changes from the client perspective?

Anyway I can have a look later to fix these points. Except you are working on this and update your PR? :-)

**Comment by rcalxrc08** [comment]
you are right, but currently i cannot make the changes.
Thank you!

**Comment by pcaspers** [comment]
no problem, I'll look into it over the weekend

**Pull request merged**
